# Generated by Django 4.2 on 2023-05-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="tbl_feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fId", models.CharField(max_length=200)),
                ("CustomerId", models.CharField(max_length=200)),
                ("feedback", models.CharField(max_length=200)),
                ("status", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "tbl_feedback",
            },
        ),
        migrations.CreateModel(
            name="tbl_foodItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("restName", models.CharField(max_length=200)),
                ("menuName", models.CharField(max_length=200)),
                ("menuItemName", models.CharField(max_length=200)),
                ("quantity", models.IntegerField()),
                ("price", models.IntegerField()),
                ("type", models.CharField(max_length=200)),
                ("cookingTime", models.TimeField()),
                ("status", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "tbl_foodItem",
            },
        ),
        migrations.CreateModel(
            name="tbl_foodMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("restName", models.CharField(max_length=200)),
                ("menuName", models.CharField(max_length=200)),
                ("type", models.CharField(max_length=200)),
                ("curine", models.CharField(max_length=200)),
                ("origin", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "tbl_foodMenu",
            },
        ),
        migrations.CreateModel(
            name="tbl_offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("restId", models.CharField(max_length=200)),
                ("menuItemName", models.CharField(max_length=200)),
                ("tbl_offer", models.IntegerField()),
                ("startDate", models.TimeField()),
                ("endDate", models.TimeField()),
                ("details", models.CharField(max_length=200)),
                ("status", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "tbl_offer",
            },
        ),
        migrations.CreateModel(
            name="tbl_restAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=200)),
                ("password", models.CharField(max_length=200)),
                ("restName", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("restId", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "tbl_restAdmin",
            },
        ),
        migrations.CreateModel(
            name="tbl_restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstName", models.CharField(max_length=200)),
                ("lastName", models.CharField(max_length=200)),
                ("restaurantName", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
                ("typeOfShop", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.IntegerField()),
                ("noOfStaff", models.IntegerField()),
                ("authPerson", models.CharField(max_length=200)),
                ("pEmail", models.EmailField(max_length=254)),
                ("pContact", models.IntegerField()),
            ],
            options={
                "db_table": "tbl_restaurant",
            },
        ),
        migrations.CreateModel(
            name="tbl_user",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstName", models.CharField(max_length=200)),
                ("lastName", models.CharField(max_length=200)),
                ("gender", models.CharField(max_length=200)),
                ("phone", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("address", models.CharField(max_length=200)),
                ("district", models.CharField(max_length=200)),
                ("state", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "tbl_user",
            },
        ),
    ]
