# Generated by Django 4.2 on 2023-05-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proapp1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tbl_user",
            name="status",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tbl_user",
            name="userName",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
