# Generated by Django 4.2 on 2023-05-10 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("proapp1", "0002_tbl_user_status_tbl_user_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tbl_user",
            old_name="userName",
            new_name="username",
        ),
    ]
