# Generated by Django 4.2 on 2023-05-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proapp1", "0004_rename_firstname_tbl_user_firstname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tbl_restaurant",
            name="status",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
