# Generated by Django 4.2 on 2023-05-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proapp1", "0006_tbl_restadmin_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tbl_offer",
            name="tbl_offer",
        ),
        migrations.AddField(
            model_name="tbl_offer",
            name="offer",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tbl_offer",
            name="endDate",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="tbl_offer",
            name="startDate",
            field=models.CharField(max_length=200),
        ),
    ]
