# Generated by Django 4.2 on 2023-06-20 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("proapp1", "0008_tbl_restaurant_password_tbl_restaurant_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tbl_foodmenu",
            old_name="curine",
            new_name="cuisine",
        ),
    ]
