# Generated by Django 4.2 on 2023-06-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proapp1", "0009_rename_curine_tbl_foodmenu_cuisine"),
    ]

    operations = [
        migrations.CreateModel(
            name="tbl_cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=200)),
                ("restName", models.CharField(max_length=200)),
                ("foodItemName", models.CharField(max_length=200)),
                ("quantity", models.IntegerField()),
                ("price", models.IntegerField()),
                ("status", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "tbl_cart",
            },
        ),
        migrations.CreateModel(
            name="tbl_order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=200)),
                ("restName", models.CharField(max_length=200)),
                ("totalPrice", models.IntegerField()),
                ("status", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "tbl_order",
            },
        ),
    ]
